; =============================================================================================
; GAME CONSTANTS
; =============================================================================================
; --- STAR BUTTON -----------------------------------------------------------------------------
BUTPOSX     EQU     220                       ; STAR BUTTON POSITION IN X
BUTPOSY     EQU     295                       ; STAR BUTTON POSITION IN Y
BUTWIDTH    EQU     100
BUTHEIGH    EQU     50

; --- MAP CONTANTS ----------------------------------------------------------------------------
BLCWIDTH    EQU     32                       ; BLOCK WIDTH
BLCHEIGH    EQU     32                       ; BLOCK HEIGH

    ; --- BLOCK 1 -----------------------------------------------------------------------------
B1SIZEH     EQU     18
B1SIZEW     EQU     32

    ; --- BLOCK 2 -----------------------------------------------------------------------------

; --- MARIO RELATED CONSTANTS ----------------------------------------------------

MASPEED     EQU     8                      ; MARNITUDE OF THE X AND Y VEL
MAWIDTH     EQU     30                      ; MARIO WIDHT
MAJUMPT     EQU     4                      ; WHEN MARIO JUMP, X TIME TO UP THE COORDINATE
MAHEIGHT    EQU     40                      ; MARIO HEIGHT

 ; --- MARIO COLISION CONSTANTS -----------------------------------------------
MACOLW      EQU     24                      ; MARIO COLISION WIDHT

; --- DONKEY_KONG RELATED CONSTANTS ----------------------------------------------------

DKWIDTH     EQU     90                       ; DONKEY_KONG WIDTH
DKHEIGHT    EQU     70                       ; DONKEY_KONG HEIGHT
DKPOSX      EQU     85                       ; DONKEY_KONG X POSITION
DKPOSY      EQU     -5                       ; DONKEY_KONG Y POSITION
DKCONTTN    EQU     18000                   ; COUNTER FOR THROWING IMAGE

; --- PEACH RELATED CONSTANTS ----------------------------------------------------

PCHWIDTH    EQU     90                       ; PEACH WIDTH
PCHHEIGH    EQU     70                       ; PEACH HEIGHT
PCHPOSX     EQU     380                      ; PEACH X POSITION


; --- BARREL RELATED CONSTANTS ----------------------------------------------------

BRLRAD      EQU     11
BRLACC      EQU     1                      ; MAGNITUDE OF THE X AND Y VEL.
BRLPCOL     EQU     $00000080               ; BARREL COLOR 
BRLFCOL     EQU     $000000FF

;---HAMMER RELATED CONSTANTS ------------------------------------------------------

HMRWIDTH    EQU     30                     ; BARREL WIDTH
HMRHEIGH    EQU     40                      ; BARREL HEIGHT

CONT        EQU     2000
      

*~Font name~Courier New~
*~Font size~12~
*~Tab type~1~
*~Tab size~4~
