; =============================================================================================
; TITLE       :
; DESCRIPTION :
; AUTHOR      :
; HISTORY     :
; =============================================================================================
			
			ORG    $1000
START		; esto es una prueba
			SIMHALT             

			END    START

*~Font name~Courier New~
*~Font size~12~
*~Tab type~1~
*~Tab size~4~
