; =============================================================================================
; SYSTEM CONSTANTS
; =============================================================================================

; --- SCREEN RELATED CONSTANTS ----------------------------------------------------------------

SCRWIDTH    EQU     640                 ; SCREEN WIDTH
SCRHEIGH    EQU     480                 ; SCREEN HEIGHT

; --- TRAP RELATED CONSTANTS ------------------------------------------------------------------
TRNDBUFF    EQU     1                   ; DOUBLE BUFFER TRAP NUMBER




*~Font name~Courier New~
*~Font size~12~
*~Tab type~1~
*~Tab size~4~
