; =============================================================================================
; GAME VARIABLES
; =============================================================================================

; --- Mario point -----------------------------------------------------------------------------
MAPOINTX     DS.W    1           ; MARIO X COORDINATE
MAPOINTY     DS.W    1           ; MARIO Y COORDINATE
MAIMAGE      DS.L    1           ; CURRENT IMAGE MARIO


*~Font name~Courier New~
*~Font size~12~
*~Tab type~1~
*~Tab size~4~
