; =============================================================================================
; GAME VARIABLES
; =============================================================================================

; --- Mario variables --------------------------------------------------------------------------
MAPOINTX     DS.W    1           ; MARIO X COORDINATE
MAPOINTY     DS.W    1           ; MARIO Y COORDINATE
MAIMAGE      DS.L    1           ; CURRENT IMAGE MARIO
MACONT       DS.B    1           ; COUNTER FOR CHANGES OF IMAGES
             DS.W    0
;--- Donkey kong variables ---------------------------------------------------------------------
DKIMAGE      DS.L    1           ; CURRENT IMAGE DK
DKCONTT      DS.W    1           ; COUNTER FOR THROWING BARRELS
DKCONT       DS.W    1           ; COUNTER FOR CHANGES OF IMAGES
             
*~Font name~Courier New~
*~Font size~12~
*~Tab type~1~
*~Tab size~4~
